myland/models.py
from myland import db


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(200), nullable=False)
    content = db.Column(db.Text, nullable=False)
    create_date = db.Column(db.DateTime(), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id', ondelete='CASCADE'), nullable=False)
    user = db.relationship('User', backref=db.backref('post_set'))
    modify_date = db.Column(db.DateTime(), nullable=True)


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(150), unique=True, nullable=False)
    password = db.Column(db.String(200), nullable=True)
    email = db.Column(db.String(120), unique=True, nullable=False)
    modify_date = db.Column(db.DateTime(), nullable=True)

myland/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, PasswordField, EmailField
from wtforms.validators import DataRequired, Length, EqualTo, Email


class PostForm(FlaskForm):
    title = StringField('제목', validators=[DataRequired('제목을 입력하세요.')])
    content = TextAreaField('내용', validators=[DataRequired('내용을 입력하세요.')])


class UserCreateForm(FlaskForm):
    username = StringField('사용자이름', validators=[DataRequired(), Length(min=3, max=25)])
    password1 = PasswordField('비밀번호', validators=[DataRequired(), EqualTo('password2', '비밀번호가 일치하지 않습니다.')])
    password2 = PasswordField('비밀번호확인', validators=[DataRequired()])
    email = EmailField('이메일', validators=[DataRequired(), Email()])


class UserLoginForm(FlaskForm):
    username = StringField('사용자이름', validators=[DataRequired(), Length(min=3, max=25)])
    password = PasswordField('비밀번호', validators=[DataRequired()])

myland/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from sqlalchemy import MetaData
import config

naming_convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}
db = SQLAlchemy(metadata=MetaData(naming_convention=naming_convention))
migrate = Migrate()


def create_app():
    app = Flask(__name__)
    app.config.from_object(config)  # config.py에 있는 설정들 애플리케이션 객체에 적용
    
    # ORM
    db.init_app(app)
    if app.config['SQLALCHEMY_DATABASE_URI'].startswith('sqlite'):
        migrate.init_app(app, db, render_as_batch=True)
    else:
        migrate.init_app(app, db)
    from . import models  # 데이터 모델 가져옴
    
    # Blueprint
    # 블루브린트 사용이 없다면 create_app 함수 내부에 계속 라우트 함수를 추가해야 함 (hello_pybo같은)
    from .views import main_views, post_views, auth_views
    app.register_blueprint(main_views.bp)
    app.register_blueprint(post_views.bp)
    app.register_blueprint(auth_views.bp)
    
    # 필터
    from .filter import format_datetime
    app.jinja_env.filters['datetime'] = format_datetime
    
    return app

myland/views/auth_views.py
import functools
from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect
from .. import db
from ..forms import UserCreateForm, UserLoginForm
from ..models import User

bp = Blueprint('auth', __name__, url_prefix='/auth')


@bp.route('/signup/', methods=('GET', 'POST'))
def signup():
    form = UserCreateForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            user = User(username=form.username.data, password=generate_password_hash(form.password1.data), email=form.email.data)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.index'))
        else:
            flash('이미 존재하는 사용자입니다.')
    return render_template('auth/signup.html', form=form)


@bp.route('/login/', methods=('GET', 'POST'))
def login():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            error = '존재하지 않는 사용자입니다.'
        elif not check_password_hash(user.password, form.password.data):
            error = '비밀번호가 올바르지 않습니다.'
        if error is None:
            session.clear()
            session['user_id'] = user.id
            return redirect(url_for('main.index'))
        flash(error)
    return render_template('auth/login.html', form=form)


@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)


@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index'))


def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))
        return view(**kwargs)
    return wrapped_view

myland/views/main_views.py
from flask import Blueprint, url_for
from werkzeug.utils import redirect
from ..models import Post

bp = Blueprint('main', __name__, url_prefix='/')


@bp.route('/')
def index():
    return redirect(url_for('post._list'))

myland/views/post_views.py
from flask import Blueprint, render_template, request, url_for, g, flash
from werkzeug.utils import redirect
from .. import db
from ..models import Post
from ..forms import PostForm
from .auth_views import login_required
from datetime import datetime

bp = Blueprint('post', __name__, url_prefix='/post')


@bp.route('/list/')
def _list():
    page = request.args.get('page', type=int, default=1)
    post_list = Post.query.order_by(Post.create_date.desc())
    post_list = post_list.paginate(page, per_page=10)
    return render_template('post/post_list.html', post_list=post_list)


@bp.route('/detail/<int:post_id>/')
def detail(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post/post_detail.html', post=post)


@bp.route('/create/', methods=('GET', 'POST'))
@login_required
def create():
    form = PostForm()
    if request.method == 'POST' and form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, create_date=datetime.now(), user=g.user)
        db.session.add(post)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('post/post_form.html', form=form)


@bp.route('/modify/<int:question_id>', methods=('GET', 'POST'))
@login_required
def modify(post_id):
    post = Post.query.get_or_404(post_id)
    if g.user != post.user:
        flash('수정권한이 없습니다.')
        return redirect(url_for('post.detail', post_id=post_id))
    if request.method == 'POST':
        form = PostForm()
        if form.validate_on_submit():
            form.populate_obj(post)
            post.modify_date = datetime.now()
            db.session.commit()
            return redirect(url_for('post.detail', post_id=post_id))
        else:
            form = PostForm(obj=post)
        return render_template('post/post_form.html', form=form)

myland/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
  <!-- Required Meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">  <!-- myland CSS -->
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
  <title>Myland</title>
</head>
<body class="bg-secondary pt-5 mt-2">

  <!-- 내비게이션 바 Start -->
  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="{{ url_for('main.index') }}">Myland</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        {% if g.user %}
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a href="{{ url_for('auth.logout') }}" class="nav-link">{{ g.user.username }} (로그아웃)</a>
          </li>
        </ul>
        {% else %}
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <!-- <a class="nav-link active" aria-current="page" href="#">계정생성</a> -->
            <a class="nav-link" href="{{ url_for('auth.signup') }}">계정생성</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.login') }}">로그인</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled">Disabled</a>
          </li>
        </ul>
        {% endif %}
        <!-- <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form> -->
      </div>
    </div>
  </nav>
  <!-- 내비게이션 바 End -->

  <!-- 기본 템플릿 안에 삽입될 내용 Start -->
  {% block content %}
  {% endblock %}
  <!-- 기본 템플릿 안에 삽입될 내용 End -->

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

myland/templates/form_errors.html
<!-- 필드 오류 -->
{% for field, errors in form.errors.items() %}
<div class="alert alert-danger" role="alert">
  <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
</div>
{% endfor %}
<!-- flash 오류 -->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
  {{ message }}
</div>
{% endfor %}

myland/templates/post/post_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
  <h2 class="border-bottom py-2 text-white">{{ post.title }}</h2>
  <div class="card my-3 text-white bg-dark">
    <div class="card-body">
      <div class="card-text" style="white-space: pre-line;">{{ post.content }}</div>
      <div class="d-flex justify-content-end">
        <div class="badge badge-light p-2 text-left">
          <div class="mb-2">{{ post.user.username }}</div>
          <div>{{ post.create_date|datetime }}</div>
        </div>
      </div>
      {% if g.user == post.user %}
      <div class="my-3">
        <a href="{{ url_for('post.modify', post_id=post.id) }}" class="btn btn-sm btn-outline-secondary">수정</a>
      </div>
      {% endif %}
    </div>
  </div>
  <!-- 원래 답변 넣는 구간 -->
  <!-- <textarea {% if not g.user %}disabled{% endif %} name="content" id="content" class="form-control" rows="10"></textarea> -->
</div>
{% endblock %}

myland/templates/post/post_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container text-white">
  <h5 class="my-3 border-bottom pb-2">게시글 등록</h5>
  <form method="post" class="post-form my-3">
    {{ form.csrf_token }}
    <!-- 오류 표시 Start -->
    {% for field, errors in form.errors.items() %}
    <div class="alert alert-danger" role="alert">
      <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
    </div>
    {% endfor %}
    <!-- 오류 표시 End -->
    <div class="form-group mb-3">
      <label for="title">제목</label>
      <input type="text" class="form-control" name="title" id="title" value="{{ form.title.data or '' }}">
    </div>
    <div class="form-group mb-3">
      <label for="content">내용</label>
      <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.data or '' }}</textarea>
    </div>
    <button type="submit" class="btn btn-primary">저장하기</button>
  </form>
</div>
{% endblock %}

myland/templates/post/post_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
  <table class="table table-dark table-striped table-hover">
    <thead>
    <tr class="text-center">
      <th>번호</th>
      <th style="width:50%">제목</th>
      <th>글쓴이</th>
      <th>작성일시</th>
    </tr>
    </thead>
    <tbody>
    {% if post_list %}
    {% for post in post_list.items %}
    <tr class="text-center">
      <td>{{ post_list.total - ((post_list.page - 1) * post_list.per_page) - loop.index0 }}</td>
      <td class="text-left">
        <a href="{{ url_for('post.detail', post_id=post.id) }}" style="text-decoration-line: none; color: white;">{{ post.title }}</a>
        <!-- 댓글 개수 표시 예정 -->
      </td>
      <td>{{ post.user.username }}</td>
      <td>{{ post.create_date|datetime }}</td>
    </tr>
    {% endfor %}
    {% else %}
    <tr>
      <td colspan="3">게시글이 없습니다.</td>
    </tr>
    {% endif %}
    </tbody>
  </table>

  <!-- 페이징 처리 Start -->
  <ul class="pagination justify-content-center">
    <!-- 이전 페이지 -->
    {% if post_list.has_prev %}
    <li class="page-item">
      <a class="page-link" href="?page={{ post_list.prev_num }}">이전</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
    </li>
    {% endif %}
    {% for page_num in post_list.iter_pages() %}
      {% if page_num %}
        {% if page_num != post_list.page %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
        </li>
        {% else %}
        <li class="page-item active" aria-current="page">
          <a class="page-link" href="#">{{ page_num }}</a>
        </li>
        {% endif %}
      {% else %}
        <li class="disabled">
          <a class="page-link" href="#">...</a>
        </li>
      {% endif %}
    {% endfor %}
    <!-- 다음 페이지 -->
    {% if post_list.has_next %}
    <li class="page-items">
      <a class="page-link" href="?page={{ post_list.next_num }}">다음</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
    </li>
    {% endif %}
  </ul>
  <!-- 페이징 처리 End -->

  <a href="{{ url_for('post.create') }}" class="btn btn-primary">게시글 등록</a>
</div>
{% endblock %}